apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scraper
spec:
  serviceName: "scraper-service"
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: {{ .Values.scraperImage.name }}
          imagePullPolicy: {{ .Values.scraperImage.imagePullPolicy }}
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "100m"
          ports:
          - containerPort: 5000
          env:
          - name: MYSQL_USER # Setting USER username on mysql From a 'Secret'
            valueFrom:
              secretKeyRef:
                name: db-root-credentials-flask
                key: username
          - name: MYSQL_PASSWORD # Setting USER username on mysql From a 'Secret'
            valueFrom:
              secretKeyRef:
                name: db-root-credentials-flask
                key: password
          - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
            valueFrom:
              configMapKeyRef:
                name: db-conf-flask
                key: name
          - name: MYSQL_HOST # Setting Database Name from a 'ConfigMap'
            valueFrom:
              configMapKeyRef:
                name: db-conf-flask
                key: host
